name: front-end unit tests

on:
  push:
    branches: [ master ]
    paths:
      - 'front-end/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'front-end/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd front-end/react-portal
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
