name: back end unit tests

on:
  push:
    branches: [ master ]
    paths:
      - 'back_end/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'back_end/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code.
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: back_end/generic-bot
    - name: Build project with gradle
      run: ./gradlew build
      working-directory: back_end/generic-bot
    - name: Run tests with gradle
      run: ./gradlew test
      working-directory: back_end/generic-bot    
