name: front-end tests and deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'front-end/**'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout code.
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up node in CI mode.
      run: npm ci
      working-directory: front-end/react-portal
    - name: Build project.
      run: npm run build --if-present
      working-directory: front-end/react-portal
    - name: Run tests.
      run: npm test
      working-directory: front-end/react-portal
      env:
        CI: true
  deploy:
    needs: unit-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout code.
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up node in CI mode.
      run: npm ci
      working-directory: front-end/react-portal
    - name: Deploy project.
      run: npm run deploy
      working-directory: front-end/react-portal
